use_frameworks! :linkage => :static

platform :ios, '14.0'

target 'FlagshipFeatureFlags_Example' do
  pod 'FlagshipFeatureFlags', :path => '../'

  target 'FlagshipFeatureFlags_Tests' do
    inherit! :search_paths
  pod 'Quick'
  pod 'Nimble'
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      # Disable code signing for frameworks to avoid sandbox issues
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end
end
